"""LLM-based dance selection agent focused on long-term coherence.

Both LODGE and EDGE stitch shorter segments into a long-form dance, so the agent is
asked to reason primarily about how coherent each dance stays across the whole song
(smooth seams, no jitter/jumps, stable foot planting, sustained musical sync without
freezing or looping), using per-window temporal trends. Beat-sync and diversity are
secondary tie-breakers.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass

from agentlodge.audio.preprocess import SongMetadata
from agentlodge.dance.metrics import DanceMetrics

RUBRIC_DIMENSIONS = (
    "smoothness",
    "seam_quality",
    "sustained_sync",
    "foot_stability",
    "variety",
    "overall_coherence",
)


@dataclass
class SelectionResult:
    selected_model: str
    reasoning: str
    analysis: str = ""
    scores: dict | None = None
    used_fallback: bool = False


def _fmt_coherence(metrics: DanceMetrics) -> str:
    if metrics.coherence is None:
        return "  (coherence signals unavailable)"
    c = metrics.coherence.to_dict()
    return (
        f"  smoothness_jerk (lower=smoother): {c['smoothness_jerk']}\n"
        f"  jitter_accel (lower=less jitter): {c['jitter_accel']}\n"
        f"  seam_spikiness (higher=sudden stitch jumps): {c['seam_spikiness']}\n"
        f"  foot_skating (lower=feet stay planted): {c['foot_skating']}\n"
        f"  contact_flicker per sec (lower=stabler planting): {c['contact_flicker']}\n"
        f"  beat_sync_trend over time (negative=sync degrades): {c['bas_trend']}\n"
        f"  energy_stability std (lower=steadier): {c['energy_stability']}\n"
        f"  per-window energy: {c['window_energy']}\n"
        f"  per-window beat_sync: {c['window_bas']}\n"
        f"  per-window smoothness_jerk: {c['window_smoothness']}\n"
        f"  window-to-window variety (too low=frozen/looping, too high=incoherent): {c['window_variety']}"
    )


def _build_prompt(
    lodge_metrics: DanceMetrics,
    edge_metrics: DanceMetrics,
    metadata: SongMetadata,
) -> str:
    return f"""You are selecting the better long-form dance for a music-driven choreography task.
Both candidates are generated by stitching shorter segments together, so your PRIMARY
criterion is LONG-TERM COHERENCE across the whole song. Beat synchronization and motion
diversity are only secondary tie-breakers.

Song:
- duration_seconds: {metadata.duration_seconds:.2f}
- estimated_bpm: {metadata.bpm:.1f}

Judge long-term coherence from these signals:
- Smooth transitions across stitch seams: low smoothness_jerk and low seam_spikiness.
- Little high-frequency jitter: low jitter_accel.
- Stable, believable foot planting: low foot_skating and low contact_flicker.
- Musical sync that HOLDS over time: per-window beat_sync should stay high and not trend
  downward (watch beat_sync_trend and the per-window beat_sync array).
- Sustained, varied motion that neither freezes/loops (variety ~0) nor jumps incoherently.

LODGE:
- beat_alignment_score: {lodge_metrics.beat_alignment_score:.4f}
- motion_diversity: {lodge_metrics.motion_diversity:.4f}
- summary: {lodge_metrics.summary}
- coherence:
{_fmt_coherence(lodge_metrics)}

EDGE:
- beat_alignment_score: {edge_metrics.beat_alignment_score:.4f}
- motion_diversity: {edge_metrics.motion_diversity:.4f}
- summary: {edge_metrics.summary}
- coherence:
{_fmt_coherence(edge_metrics)}

Think step by step. First analyze each candidate's coherence over time (seams, jitter,
foot stability, whether sync/energy hold across windows, and whether it stays varied
without looping). Then score each candidate from 1 (poor) to 5 (excellent) on:
{", ".join(RUBRIC_DIMENSIONS)}. Prioritize overall_coherence; use beat sync and diversity
only to break ties. Then choose the more coherent long-form dance.

Respond with JSON only, in this exact shape:
{{"analysis": "your step-by-step comparison",
  "scores": {{"lodge": {{"smoothness": 0, "seam_quality": 0, "sustained_sync": 0, "foot_stability": 0, "variety": 0, "overall_coherence": 0}},
              "edge": {{"smoothness": 0, "seam_quality": 0, "sustained_sync": 0, "foot_stability": 0, "variety": 0, "overall_coherence": 0}}}},
  "selected_model": "lodge" or "edge",
  "reasoning": "brief justification grounded in long-term coherence"}}
"""


def _parse_response(text: str) -> SelectionResult:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError("Agent response did not contain JSON")
    payload = json.loads(match.group())
    selected = str(payload["selected_model"]).lower().strip()
    if selected not in {"lodge", "edge"}:
        raise ValueError(f"Invalid selected_model: {selected}")
    scores = payload.get("scores")
    return SelectionResult(
        selected_model=selected,
        reasoning=str(payload.get("reasoning", "")).strip(),
        analysis=str(payload.get("analysis", "")).strip(),
        scores=scores if isinstance(scores, dict) else None,
    )


def select_dance(
    lodge_metrics: DanceMetrics,
    edge_metrics: DanceMetrics,
    metadata: SongMetadata,
    api_key: str | None,
) -> SelectionResult:
    if not api_key:
        return SelectionResult(
            selected_model="lodge",
            reasoning="No OPENAI_API_KEY configured; defaulting to LODGE.",
            used_fallback=True,
        )

    try:
        import os

        from openai import OpenAI

        client = OpenAI(api_key=api_key)
        model = os.getenv("OPENAI_CHAT_MODEL", "gpt-4o-mini")
        response = client.chat.completions.create(
            model=model,
            max_tokens=800,
            messages=[
                {
                    "role": "user",
                    "content": _build_prompt(lodge_metrics, edge_metrics, metadata),
                }
            ],
        )
        text = response.choices[0].message.content or ""
        return _parse_response(text)
    except Exception as exc:
        return SelectionResult(
            selected_model="lodge",
            reasoning=f"Selection agent failed ({exc}); defaulting to LODGE.",
            used_fallback=True,
        )
